# Generated by Django 5.2.7 on 2025-10-23 02:28

import datetime
from decimal import Decimal

from django.db import migrations
from django.utils import timezone
from django.utils.text import slugify


def seed_initial_data(apps, schema_editor):
    City = apps.get_model("main", "City")
    Category = apps.get_model("main", "Category")
    Venue = apps.get_model("main", "Venue")
    VenuePhoto = apps.get_model("main", "VenuePhoto")
    AddOn = apps.get_model("main", "AddOn")
    TimeSlot = apps.get_model("main", "TimeSlot")

    cities = {
        name: City.objects.get_or_create(name=name, defaults={"slug": slugify(name)})[0]
        for name in ["Jakarta", "Bandung", "Surabaya", "Yogyakarta", "Bali"]
    }

    categories = {
        name: Category.objects.get_or_create(name=name, defaults={"slug": slugify(name)})[0]
        for name in ["Football", "Futsal", "Basketball", "Badminton", "Volleyball"]
    }

    venues_data = [
        {
            "name": "Jakarta Elite Arena",
            "city": "Jakarta",
            "category": "Football",
            "price": Decimal("350000"),
            "image": "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80",
            "address": "Jl. Sudirman No. 12, Jakarta",
            "surface": "Hybrid Grass",
            "amenities": "Locker Room, LED Lighting, Pro Audio",
            "description": "Stadion mini premium dengan permukaan rumput hybrid dan fasilitas modern cocok untuk laga persahabatan atau turnamen skala kecil.",
            "photos": [
                "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80",
                "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80",
            ],
        },
        {
            "name": "Bandung Velocity Futsal",
            "city": "Bandung",
            "category": "Futsal",
            "price": Decimal("180000"),
            "image": "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80",
            "address": "Jl. Riau No. 45, Bandung",
            "surface": "Synthetic Turf",
            "amenities": "Changing Room, Scoreboard, Cafe",
            "description": "Lapangan futsal indoor dengan pencahayaan optimal dan sistem pendingin yang menjaga kenyamanan pertandingan sepanjang hari.",
            "photos": [
                "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80",
            ],
        },
        {
            "name": "Surabaya Sky Dome",
            "city": "Surabaya",
            "category": "Basketball",
            "price": Decimal("250000"),
            "image": "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=1200&q=80",
            "address": "Jl. Darmo Permai, Surabaya",
            "surface": "Maple Wood",
            "amenities": "Shot Clock, Medical Room, VIP Lounge",
            "description": "Arena basket bergaya NBA dengan penonton tribun 360°, cocok untuk scrimmage maupun turnamen kampus.",
            "photos": [
                "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=80",
            ],
        },
        {
            "name": "Jogja Volley Center",
            "city": "Yogyakarta",
            "category": "Volleyball",
            "price": Decimal("150000"),
            "image": "https://images.unsplash.com/photo-1504457047772-27faf1c00561?auto=format&fit=crop&w=1200&q=80",
            "address": "Jl. Kaliurang Km 8, Sleman",
            "surface": "Cushion Court",
            "amenities": "Shower, Equipment Rental, Live Streaming Rig",
            "description": "Lapangan voli indoor dengan standar nasional dan kamera live streaming untuk mengabadikan setiap rally.",
            "photos": [
                "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80",
            ],
        },
        {
            "name": "Bali Sunset Court",
            "city": "Bali",
            "category": "Badminton",
            "price": Decimal("220000"),
            "image": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
            "address": "Jl. Petitenget, Badung",
            "surface": "PVC Tournament",
            "amenities": "Air Conditioner, Private Lounge, Coach on Demand",
            "description": "Arena bulu tangkis eksklusif bernuansa tropis dengan lounge pribadi dan akses coach profesional sesuai permintaan.",
            "photos": [
                "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80",
            ],
        },
    ]

    venue_map = {}
    for data in venues_data:
        city = cities[data["city"]]
        category = categories[data["category"]]
        slug = slugify(data["name"])
        venue, _ = Venue.objects.update_or_create(
            slug=slug,
            defaults={
                "name": data["name"],
                "city": city,
                "category": category,
                "price_per_hour": data["price"],
                "cover_image": data["image"],
                "address": data["address"],
                "surface_type": data["surface"],
                "amenities": data["amenities"],
                "description": data["description"],
            },
        )
        venue.photos.all().delete()
        for photo_url in data["photos"]:
            VenuePhoto.objects.create(venue=venue, image_url=photo_url)
        venue_map[slug] = venue

    addons_data = [
        ("Match Referee", Decimal("50000"), ["jakarta-elite-arena", "surabaya-sky-dome"]),
        ("Hydration Package", Decimal("30000"), list(venue_map.keys())),
        ("Scoreboard Operator", Decimal("40000"), ["jakarta-elite-arena", "bandung-velocity-futsal"]),
        ("Sports Photographer", Decimal("60000"), ["bali-sunset-court", "surabaya-sky-dome"]),
    ]

    for name, price, venue_slugs in addons_data:
        addon, _ = AddOn.objects.update_or_create(name=name, defaults={"price": price})
        addon.venues.set([venue_map[slug] for slug in venue_slugs if slug in venue_map])

    today = timezone.localdate()
    slot_templates = [
        (datetime.time(7, 0), datetime.time(9, 0)),
        (datetime.time(16, 0), datetime.time(18, 0)),
        (datetime.time(19, 0), datetime.time(21, 0)),
    ]

    for venue in venue_map.values():
        for offset in range(1, 8):
            date_value = today + datetime.timedelta(days=offset)
            for start, end in slot_templates:
                TimeSlot.objects.get_or_create(
                    venue=venue,
                    date=date_value,
                    start_time=start,
                    end_time=end,
                )


def unseed_initial_data(apps, schema_editor):
    Venue = apps.get_model("main", "Venue")
    AddOn = apps.get_model("main", "AddOn")
    TimeSlot = apps.get_model("main", "TimeSlot")
    VenuePhoto = apps.get_model("main", "VenuePhoto")

    TimeSlot.objects.all().delete()
    VenuePhoto.objects.all().delete()
    AddOn.objects.all().delete()
    Venue.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_initial_data, unseed_initial_data),
    ]
